version: '3'
services:
    web:
        container_name: web
        build: .
        volumes:
            - .:/src
        command: python3 /src/TrendMap/manage.py runserver 0.0.0.0:8000
        ports:
            - "8000:8000"
    mongo:
        container_name: mongo
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
    mongo-express:
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
